Repository codesquad-members-2024/be-chess, pull requests merged in 2024-03, with the labels that each got.

#1 [Soap] Step-1 체스 구현 시작하기
  Pawn.java
  PawnTest.java
  README.md
Labels: Step2-1

#14 [미르] Step-1 체스 프로젝트 시작
  build.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#15 [제이든] step-1 체스 프로젝트 시작
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#3 senna step-1 be-chess
  .gitignore
  src/units/Pawn.java
  test/units/PawnTest.java
Labels: Step2-1

#4 [코리] step-1 체스 프로젝트 시작
  Pawn.java
  PawnTest.java
Labels: Step2-1

#5 [샤피] step-1 체스 구현 시작하기
  build.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#20 [웨이드] step-1 체스 프로젝트 시작
  Pawn.java
  PawnTest.java
Labels: Step2-1

#24 [Zoonmy] BE-Chess : step - 1
  .github/workflows/merge.yml
  .gitignore
  build.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#6 [상추] step-1 체스 프로젝트 시작
  .github/pull_request_template.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/chesspiece/Pawn.java
  src/test/java/chesspiece/PawnTest.java
Labels: Step2-1

#7 [zzawang] step-1 체스 구현 시작하기
  build.gradle
  piece/Pawn.java
  src/main/java/piece/Pawn.java
  src/test/java/PawnTest.java
  test/PawnTest.java
Labels: Step2-1

#8 [Soap] Step-2 : 체스판 생성
  .gitignore
  .gradle/7.5.1/checksums/checksums.lock
  .gradle/7.5.1/checksums/md5-checksums.bin
  .gradle/7.5.1/checksums/sha1-checksums.bin
  .gradle/7.5.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.5.1/dependencies-accessors/gc.properties
  .gradle/7.5.1/executionHistory/executionHistory.bin
  .gradle/7.5.1/executionHistory/executionHistory.lock
  .gradle/7.5.1/fileChanges/last-build.bin
  .gradle/7.5.1/fileHashes/fileHashes.bin
  .gradle/7.5.1/fileHashes/fileHashes.lock
  .gradle/7.5.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/vcs-1/gc.properties
  Pawn.java
  PawnTest.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#11 [심바] step-1 체스 프로젝트 시작
  main/Pawn.java
  test/PawnTest.java
Labels: Step2-1

#12 [이브이] step-1 체스 구현 시작
  .idea/.gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#19 [Alex] step-1 체스 프로젝트 시작
  untitled/src/main/java/org/example/Color.java
  untitled/src/main/java/org/example/Pawn.java
  untitled/src/test/java/PawnTest.java
Labels: Step2-1

#22 [망고] step-1 체스 프로젝트 시작
  .github/workflows/merge.yml
  .gradle/8.4/checksums/checksums.lock
  .gradle/8.4/checksums/md5-checksums.bin
  .gradle/8.4/checksums/sha1-checksums.bin
  .gradle/8.4/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.4/dependencies-accessors/gc.properties
  .gradle/8.4/executionHistory/executionHistory.bin
  .gradle/8.4/executionHistory/executionHistory.lock
  .gradle/8.4/fileChanges/last-build.bin
  .gradle/8.4/fileHashes/fileHashes.bin
  .gradle/8.4/fileHashes/fileHashes.lock
  .gradle/8.4/fileHashes/resourceHashesCache.bin
  .gradle/8.4/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/aws.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/be-chess.main.iml
  .idea/modules/be-chess.test.iml
  .idea/vcs.xml
  README.md
  build.gradle
  build/reports/tests/test/classes/PawnTest.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/default-package.html
  build/test-results/test/TEST-PawnTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#23 [코리] step-2 체스판 생성
  Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#31 [yelly] step-2 체스판 생성
  README.md
  src/main/java/chess/board/Board.java
  src/main/java/chess/common/Color.java
  src/main/java/chess/domain/Pawn.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/domain/PawnTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#33 [그로밋] step-1 체스 프로젝트 시작
  .gitattributes
  .gitignore
  chess1/build.gradle
  chess1/src/main/java/chess/piece/Color.java
  chess1/src/main/java/chess/piece/Pawn.java
  chess1/src/test/java/chess/piece/PawnTest.java
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#35 [웨이드] step-2 체스판 생성
  .gitignore
  Pawn.java
  PawnTest.java
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#27 [eddy] step-1 체스 프로젝트 시작
  .gitattributes
  .github/PawnTest.java
  .github/workflows/merge.yml
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/be-chess.main.iml
  .idea/modules/be-chess.test.iml
  .idea/vcs.xml
  build.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#37 [미르] Step-2 체스판 생성
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-2

#29 [Sid] step-1 체스 프로젝트 시작
  .gitattributes
  .gitignore
  .gitmessage.txt
  README.md
  app/build.gradle
  app/src/main/java/org/codeSquad/Pawn.java
  app/src/test/java/org/codeSquad/PawnTest.java
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#30 [Juju] step-1 체스 프로젝트 시작
  build.gradle
  settings.gradle
  src/main/java/Pawn.java
  src/main/java/Validator.java
  src/test/java/PawnTest.java
Labels: Step2-1

#32 [실브] step-1 체스 프로젝트 시작
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#40 [다오] step-1 체스 프로젝트 시작
  .gitattributes
  .gitignore
  app/.idea/.gitignore
  app/.idea/dbnavigator.xml
  app/.idea/gradle.xml
  app/.idea/misc.xml
  app/.idea/vcs.xml
  app/build.gradle
  app/src/main/java/chess/App.java
  app/src/main/java/chess/Pawn.java
  app/src/test/java/chess/PawnTest.java
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Step2-1

#39 [Soap] Step-3 : 체스판 초기화 + 리뷰 반영
  .gitignore
  src/main/java/Game.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#26 [애셔] step-1 체스 프로젝트 시작
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/be-chess.main.iml
  .idea/modules/be-chess.test.iml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#38 [Daniel] step-1 체스 구현 시작하기
  .gitignore
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#41 [zzawang] step-2 체스판 생성
  piece/Pawn.java
  src/main/java/chess/pieces/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/piece/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/pieces/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  test/PawnTest.java
Labels: Step2-2

#42 [제이든] step-2 체스판 생성
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Board/Board.java
  src/main/java/pieces/Pawn.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#45 [Soap] Step4 : 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#48 [샤피] step-2 체스판 생성
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#51 [심바] step-2 체스판 생성
  README.md
  chess/Board.java
  chess/pieces/Pawn.java
  chess/pieces/PawnTest.java
  test/BoardTest.java
Labels: Step2-2

#56 [데이] step-2 체스판 생성
  Pawn.java
  PawnTest.java
  src/chess/Colors.java
  src/chess/board/Board.java
  src/chess/pieces/Pawn.java
  src/test/board/BoardTest.java
  src/test/pieces/PawnTest.java
Labels: Step2-2

#58 [Juju] step-2 체스판 생성
  src/main/java/Pawn.java
  src/main/java/Validator.java
  src/main/java/chess/Board.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Validator.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-2

#67 [Gromit] step-2 체스판 생성
  .gitignore
  chess1/src/main/java/chess/Board.java
  chess1/src/main/java/chess/piece/Color.java
  chess1/src/main/java/chess/piece/Pawn.java
  chess1/src/main/java/chess/pieces/Color.java
  chess1/src/main/java/chess/pieces/Pawn.java
  chess1/src/test/java/chess/BoardTest.java
  chess1/src/test/java/chess/piece/PawnTest.java
  chess1/src/test/java/chess/pieces/PawnTest.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: Step2-2

#59 [Sid] step-2 체스판 생성
  README.md
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/pieces/ChessPieceColor.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/main/java/org/codeSquad/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
  app/src/test/java/org/codeSquad/PawnTest.java
Labels: Step2-2

#60 [senna] Step2
  .github/workflows/merge.yml
  .gitignore
  build.gradle
  src/main/java/chess/Board.java
  src/main/java/chess/enums/Color.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/units/Pawn.java
  test/units/PawnTest.java
Labels: Step2-2

#64 [Jin] step2-1 Pawn
  README.md
  build.gradle
  src/main/java/Pawn.java
  src/main/java/PieceColor.java
  src/test/java/PawnTest.java
Labels: Step2-1

#68 [yelly] step-3 체스 판 초기화
  .gitattributes
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/chess/ChessSimulator.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/PieceShape.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceShapeTest.java
Labels: Step2-3

#66 [eddy] step-2 체스판 생성
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/be-chess.main.iml
  .idea/modules/be-chess.test.iml
  .idea/vcs.xml
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#73 [미르] Step-3 체스판 초기화
  README.md
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/PieceColor.java
  src/main/java/pieces/Representation.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-3

#76 [망고] step-2 체스판 생성
  .github/pull_request_template.md
  .github/workflows/merge.yml
  .gitignore
  .gradle/8.4/checksums/checksums.lock
  .gradle/8.4/checksums/md5-checksums.bin
  .gradle/8.4/checksums/sha1-checksums.bin
  .gradle/8.4/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.4/dependencies-accessors/gc.properties
  .gradle/8.4/executionHistory/executionHistory.bin
  .gradle/8.4/executionHistory/executionHistory.lock
  .gradle/8.4/fileChanges/last-build.bin
  .gradle/8.4/fileHashes/fileHashes.bin
  .gradle/8.4/fileHashes/fileHashes.lock
  .gradle/8.4/fileHashes/resourceHashesCache.bin
  .gradle/8.4/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/aws.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/be-chess.main.iml
  .idea/modules/be-chess.test.iml
  .idea/vcs.xml
  README.md
  build/reports/tests/test/classes/PawnTest.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/default-package.html
  build/test-results/test/TEST-PawnTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#79 [샤피] step-3 체스판 초기화
  README.md
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#54 [코리] step-3 체스판 초기화
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/chess/Application.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Color.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#55 [zzawang] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/pieces/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/PieceSymbol.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-3

#52 [kalia] Step02-보드판 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/example/Chess/Board.java
  src/main/java/org/example/Main.java
  src/main/java/org/example/Pieces/Pawn.java
  src/test/java/Chess/BoardTest.java
  src/test/java/Pieces/PawnTest.java
  untitled/src/main/java/org/example/Pawn.java
  untitled/src/test/java/PawnTest.java
Labels: Step2-2

#80 [Soap] Step-5 : 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-5

#53 [실브] step-2 체스판 생성
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#61 [다오] step-2 체스판 생성
  .gitignore
  README.md
  app/.idea/.gitignore
  app/.idea/dbnavigator.xml
  app/.idea/gradle.xml
  app/.idea/misc.xml
  app/.idea/vcs.xml
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/Pawn.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
Labels: Step2-2

#62 [이브이] step-2 체스판 생성
  README.md
  build.gradle
  src/main/java/Board.java
  src/main/java/Main.java
  src/main/java/Pawn.java
  src/main/java/Piece.java
  src/test/java/BoardTest.java
  src/test/java/PawnTest.java
Labels: Step2-2

#70 [senna] - Step3
  src/main/java/chess/Board.java
  src/main/java/chess/Game.java
  src/main/java/chess/Main.java
  src/main/java/chess/enums/Color.java
  src/main/java/chess/enums/Order.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#77 [Daniel] step-2 체스판 생성
  .gitignore
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-2

#85 [데이] step-3 체스판 초기화
  README.md
  src/chess/Application.java
  src/chess/board/Board.java
  src/chess/pieces/Colors.java
  src/chess/pieces/Pawn.java
  src/chess/pieces/Representation.java
  src/test/board/BoardTest.java
  src/test/pieces/PawnTest.java
Labels: Step2-3

#89 [심바] step-3 체스판 초기화
  chess/Board.java
  chess/Command.java
  chess/Game.java
  chess/pieces/Color.java
  chess/pieces/Pawn.java
  chess/pieces/PawnTest.java
  test/BoardTest.java
  test/chess/pieces/PawnTest.java
Labels: Step2-3

#90 [Bon] step2-1 체스 프로젝트 시작
  .github/workflows/merge.yml
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/step2.main.iml
  .idea/modules/step2.test.iml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/Pawn.java
  src/test/java/PawnTest.java
Labels: Step2-1

#94 [Soap] Step-6 : 기물 이동 구현
  src/main/java/Game.java
  src/main/java/GameLauncher.java
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/ChessHelp.java
  src/main/java/chess/Rank.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/ChessGameTest.java
Labels: Step2-6

#97 [zzawang] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step2-4

#98 `[다오] step-3 체스판 초기화`
  README.md
  app/build.gradle
  app/src/main/java/chess/App.java
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/ChessGame.java
  app/src/main/java/chess/pieces/ChessPiece.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#101 [망고] step-3 체스판 초기화
  README.md
  src/main/java/chess/Board.java
  src/main/java/chess/Play.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#105 [Juju] step-3 보드판 초기화
  src/main/java/ChessGame.java
  src/main/java/chess/Board.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Validator.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-3

#106 [senna] - Step5
  src/main/java/chess/Board.java
  src/main/java/chess/enums/Color.java
  src/main/java/chess/enums/Position.java
  src/main/java/chess/enums/TypeOfPiece.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-5

#107 [kalia] Step03-보드판 생성
  src/main/java/org/example/Chess/Board.java
  src/main/java/org/example/Main.java
  src/main/java/org/example/Pieces/Pawn.java
  src/test/java/Chess/BoardTest.java
  src/test/java/Pieces/PawnTest.java
Labels: Step2-3

#82 [이브이] step-3 체스판 초기화
  README.md
  src/main/java/Board.java
  src/main/java/Main.java
  src/main/java/Pawn.java
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/utils/StringUtils.java
  src/test/java/BoardTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#78 [Alex] step-2 체스판 생성
  src/main/java/chess/Board.java
  src/main/java/piece/Pawn.java
  src/main/java/piece/Piece.java
  src/main/java/piece/Pieces.java
  src/test/java/board/BoardTest.java
  src/test/java/piece/PawnTest.java
  untitled/src/main/java/org/example/Color.java
  untitled/src/main/java/org/example/Pawn.java
  untitled/src/test/java/PawnTest.java
Labels: Step2-2

#88 [실브] step-3 체스판 초기화
  src/main/java/Game.java
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#110 [Sid] step-3 체스판 초기화
  README.md
  app/build.gradle
  app/src/main/java/Main.java
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/GameExecutor.java
  app/src/main/java/chess/pieces/Color.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/main/java/chess/pieces/Representation.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#112 [zzawang] step-5 기물 위치 부여 및 점수계산
  gradlew
  gradlew.bat
  src/main/java/chess/Board.java
  src/main/java/chess/Rank.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceSymbol.java
  src/main/java/utils/Position.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step2-5

#113 [Jin] step2 체스판 생성
  README.md
  build.gradle
  src/README.md
  src/main/java/Pawn.java
  src/main/java/PieceColor.java
  src/main/java/chess/Board.java
  src/main/java/chess/Coordinate.java
  src/main/java/pieces/Pawn.java
  src/test/java/PawnTest.java
  src/test/java/chess/Board.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/Coordinate.java
  src/test/java/pieces/Pawn.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-2

#116 [Bon] step2-2 체스판 생성
  .gitignore
  README.md
  src/main/java/Board.java
  src/main/java/Pawn.java
  src/main/java/pieces/Pawn.java
  src/test/java/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-2

#117 [데이] step-4 모든 기물 배치하기
  README.md
  src/chess/Application.java
  src/chess/board/Board.java
  src/chess/board/Square.java
  src/chess/pieces/Pawn.java
  src/chess/pieces/Piece.java
  src/chess/pieces/PieceType.java
  src/chess/pieces/Representation.java
  src/test/board/BoardTest.java
  src/test/pieces/PawnTest.java
  src/test/pieces/PieceTest.java
  src/utils/StringUtils.java
Labels: Step2-4

#119 [이브이] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceType.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#120 [Daniel] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/GamePlay.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/PawnColor.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-3

#121 [상추] step-6 기물 이동 구현
  build.gradle
  src/main/java/chess/Game.java
  src/main/java/chess/Main.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Position.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/game/Game.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Direction.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/NoPiece.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/main/java/chess/utils/Command.java
  src/main/java/chess/utils/ErrorMessage.java
  src/main/java/chess/view/View.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/game/GameTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
  src/test/java/chess/utils/CommandTest.java
  src/test/java/chess/view/ViewTest.java
Labels: Step2-6

#122 [eddy] step-3 체스판 초기화
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: Step2-3

#123 `[다오] step-4 모든 기물 배치하기`
  README.md
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/pieces/ChessPiece.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/main/java/chess/pieces/Piece.java
  app/src/main/java/chess/utils/StringUtils.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
  app/src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#124 [Sid] step-4 모든 기물 배치하기
  README.md
  app/src/main/java/chess/Board.java
  app/src/main/java/chess/GameExecutor.java
  app/src/main/java/chess/pieces/Name.java
  app/src/main/java/chess/pieces/Pawn.java
  app/src/main/java/chess/pieces/Piece.java
  app/src/main/java/chess/pieces/Representation.java
  app/src/main/java/utils/StringUtils.java
  app/src/test/java/chess/BoardTest.java
  app/src/test/java/chess/pieces/PawnTest.java
  app/src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#127 [실브] step-4 모든 기물 배치하기
  src/main/java/Game.java
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step2-4

#131 [Juju] step-4 모든 기물 배치하기
  src/main/java/ChessGame.java
  src/main/java/chess/Board.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step2-4

#134 [senna] - Step6
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Game.java
  src/main/java/chess/Launcher.java
  src/main/java/chess/Main.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/BoardView.java
  src/main/java/chess/enums/Direction.java
  src/main/java/chess/enums/Order.java
  src/main/java/chess/enums/Position.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/implement/Bishop.java
  src/main/java/chess/pieces/implement/Blank.java
  src/main/java/chess/pieces/implement/King.java
  src/main/java/chess/pieces/implement/Knight.java
  src/main/java/chess/pieces/implement/Pawn.java
  src/main/java/chess/pieces/implement/Queen.java
  src/main/java/chess/pieces/implement/Rook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-6

#135 [kalia] Step04 모든 기물 배치하기
  src/main/java/org/example/Chess/Board.java
  src/main/java/org/example/Chess/Main.java
  src/main/java/org/example/Pieces/Bishop.java
  src/main/java/org/example/Pieces/Color.java
  src/main/java/org/example/Pieces/King.java
  src/main/java/org/example/Pieces/Knight.java
  src/main/java/org/example/Pieces/Pawn.java
  src/main/java/org/example/Pieces/Piece.java
  src/main/java/org/example/Pieces/PieceFactory.java
  src/main/java/org/example/Pieces/Queen.java
  src/main/java/org/example/Pieces/Rook.java
  src/main/java/org/example/Utils/StringUtils.java
  src/test/java/Chess/BoardTest.java
  src/test/java/Pieces/PawnTest.java
  src/test/java/Pieces/PieceTest.java
Labels: Step2-4

#139 [Bon] step2-3 체스판 초기화
  src/main/java/Board.java
  src/main/java/pieces/Pawn.java
  src/test/java/BoardTest.java
  src/test/java/pieces/PawnTest.java
Labels: Step2-3

#141 [망고] step-4 모든 기물 배치하기
  README.md
  src/main/java/chess/Board.java
  src/main/java/chess/Play.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#136 [심바] step-4 모든 기물 배치하기
  README.md
  chess/Board.java
  chess/Game.java
  chess/pieces/Color.java
  chess/pieces/Pawn.java
  chess/pieces/Piece.java
  chess/utils/StringUtils.java
  test/BoardTest.java
  test/chess/pieces/PawnTest.java
  test/chess/pieces/PieceTest.java
Labels: Step2-4

#140 [Alex]step 3- 체스판 초기화
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/piece/Pawn.java
  src/main/java/piece/Piece.java
  src/test/java/board/BoardTest.java
  src/test/java/piece/PawnTest.java
Labels: Step2-3

#142 [Daniel] step-4 모든 기물 배치하기
  src/main/java/chess/Board.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/PieceColor.java
  src/main/java/pieces/PieceName.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
Labels: Step2-4

#143 [데이] step-5 기물 위치 부여 및 점수계산
  README.md
  src/chess/board/Board.java
  src/chess/board/Rank.java
  src/chess/board/Square.java
  src/chess/pieces/Colors.java
  src/chess/pieces/Piece.java
  src/chess/pieces/PieceType.java
  src/test/board/BoardTest.java
  src/test/pieces/PieceTest.java
  src/utils/StringUtils.java
Labels: Step2-5

#144 [상추] step-8 GUI나 웹으로 구현
  build.gradle
  src/main/java/chess/ServletApplication.java
  src/main/java/chess/ServletInitializer.java
  src/main/java/chess/board/Position.java
  src/main/java/chess/game/Game.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/servlet/HomeServlet.java
  src/main/java/chess/servlet/MainServlet.java
  src/main/java/chess/servlet/PlayServlet.java
  src/main/webApp/WEB-INF/views/chess.jsp
  src/main/webApp/WEB-INF/views/end.jsp
  src/main/webApp/WEB-INF/views/home.jsp
Labels: Step2-8

#146 [웨이드] step-4 모든 기물 배치하기
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/Game.java
  src/main/java/chess/pieces/Color.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Representation.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#145 [샤피] step-4 모든 기물 배치하기
  README.md
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Rank.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Representation.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: Step2-4

#148 [Soap] Step-7 - 2 : 보드의 기능 분배
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/ChessView.java
  src/main/java/chess/Direction.java
  src/main/java/chess/Rank.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/ChessGameTest.java
Labels: Step2-7

#149 [yelly] step-6 기물 이동 구현
  README.md
  src/main/java/chess/ChessSimulator.java
  src/main/java/chess/board/Block.java
  src/main/java/chess/board/Board.java
  src/main/java/chess/board/Game.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/CreateCommand.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Movable.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/PieceFactory.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/chess/board/BlockTest.java
  src/test/java/chess/board/BoardTest.java
  src/test/java/chess/board/GameTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/BlankTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
Labels: Step2-6

#150 [zzawang] step-6 기물 이동 구현
  .gitignore
  build.gradle
  src/main/java/Application.java
  src/main/java/chess/Board.java
  src/main/java/chess/ChessGame.java
  src/main/java/chess/Rank.java
  src/main/java/pieces/Bishop.java
  src/main/java/pieces/Blank.java
  src/main/java/pieces/Direction.java
  src/main/java/pieces/King.java
  src/main/java/pieces/Knight.java
  src/main/java/pieces/Pawn.java
  src/main/java/pieces/Piece.java
  src/main/java/pieces/Queen.java
  src/main/java/pieces/Rook.java
  src/main/java/utils/Position.java
  src/main/java/view/ChessView.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/ChessGameTest.java
  src/test/java/pieces/BishopTest.java
  src/test/java/pieces/KingTest.java
  src/test/java/pieces/KnightTest.java
  src/test/java/pieces/PawnTest.java
  src/test/java/pieces/PieceTest.java
  src/test/java/pieces/QueenTest.java
  src/test/java/pieces/RookTest.java
  src/test/java/view/ChessViewTest.java
Labels: Step2-6
